In [2]:
import pandas as pd
import numpy as np

df_tv = pd.read_csv('data/train.csv')

df_tv.head()

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,...,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,...,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,...,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,...,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,...,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,...,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low

In [ ]:
# import matplotlib.pyplot as plt
# from mlxtend.plotting import scatterplotmatrix
# scatterplotmatrix(df_tv.values, figsize=(12, 10), names=df_tv.columns, alpha=0.5)
# plt.tight_layout()
# plt.show()

/tmp/ipykernel_19294/295165879.py:4: UserWarning: Tight layout not applied. tight_layout cannot make Axes width small enough to accommodate all Axes decorations
  plt.tight_layout()

KeyboardInterrupt:

In [8]:
df_tv.isnull().sum()

id                         0
Soil_Type                  0
Soil_pH                    0
Soil_Moisture              0
Organic_Carbon             0
Electrical_Conductivity    0
Temperature_C              0
Humidity                   0
Rainfall_mm                0
Sunlight_Hours             0
Wind_Speed_kmh             0
Crop_Type                  0
Crop_Growth_Stage          0
Season                     0
Irrigation_Type            0
Water_Source               0
Field_Area_hectare         0
Mulching_Used              0
Previous_Irrigation_mm     0
Region                     0
Irrigation_Need            0
dtype: int64

In [16]:
print('Categories Crop_Type', df_tv['Crop_Type'].unique())
print('Categories Crop_Growth_Stage', df_tv['Crop_Growth_Stage'].unique())
print('Categories Season', df_tv['Season'].unique())
print('Categories Irrigation Type', df_tv['Irrigation_Type'].unique())
print('Categories Water Source', df_tv['Water_Source'].unique())
print('Categories Mulching_Used', df_tv['Mulching_Used'].unique())
print('Categories Region', df_tv['Region'].unique())
print('Categories Irrigation_Need', df_tv['Irrigation_Need'].unique())

Categories Crop_Type ['Sugarcane' 'Wheat' 'Rice' 'Potato' 'Cotton' 'Maize']
Categories Crop_Growth_Stage ['Sowing' 'Vegetative' 'Flowering' 'Harvest']
Categories Season ['Zaid' 'Kharif' 'Rabi']
Categories Irrigation Type ['Drip' 'Rainfed' 'Sprinkler' 'Canal']
Categories Water Source ['Rainwater' 'River' 'Reservoir' 'Groundwater']
Categories Mulching_Used ['No' 'Yes']
Categories Region ['East' 'South' 'North' 'West' 'Central']
Categories Irrigation_Need ['Low' 'Medium' 'High']

In [ ]:
pd.get_dummies(df_tv)

,id,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,...,Mulching_Used_No,Mulching_Used_Yes,Region_Central,Region_East,Region_North,Region_South,Region_West,Irrigation_Need_High,Irrigation_Need_Low,Irrigation_Need_Medium
0,0,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,16.79,...,True,False,False,True,False,False,False,False,True,False
1,1,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,...,False,True,False,False,False,True,False,False,True,False
2,2,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,3.85,...,False,True,False,False,True,False,False,False,True,False
3,3,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,2.31,...,False,True,False,False,False,True,False,False,False,True
4,4,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,13.94,...,True,False,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,629995,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,18.85,...,True,False,False,False,False,True,False,False,False,True
629996,629996,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,17.99,...,False,True,True,False,False,False,False,False,False,True
629997,629997,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,17.25,...,False,True,False,False,False,True,False,True,False,False
629998,629998,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,5.00,...,False,True,False,True,False,False,False,False,True,False
629999,629999,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,2.72,...,True,False,False,False,False,False,True,False,True,False

In [ ]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()